spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 116.204.65.192:8848

    gateway:
      routes:
        - id: sort_route
          uri: lb://service-sort
          predicates:
            - Path=/api/sort/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: course_route
          uri: lb://service-course
          predicates:
            - Path=/api/course/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://service-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://service-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
server:
  port: 88
