spring:
  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        server-addr: 116.204.65.192:8848

    alicloud:
      access-key: LTAI5tRpWutP7Kdvw3ZKdRez
      secret-key: KYFqX3J2zDw8suaAIMZvxObgIVMYSA
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-chenle

server:
  port: 8084
